baseURL = "https://oxipass.io/"
languageCode = "en-us"
# title = "ADA Rocket"
theme = "minimal"
# disqusShortname = "username" # delete this to disable disqus comments
googleAnalytics = ""

[params]
    author = "Alexander Bykov"
    description = "OxiPass - a free and open-source password manager"
#    githubUsername = "#"
    accent = "green"
    showBorder = true
    backgroundColor = "white"
    copyright = "[OxiPass](https://oxipass.io) © All rights reserved"
#    font = "Raleway" # should match the name on Google Fonts!
    highlight = false
    canonifyurls = true
#    highlightStyle = "default"
#    highlightLanguages = ["go", "haskell", "kotlin", "scala", "swift"]

[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

[[menu.main]]
url = "/roadmap/"
name = "Roadmap"
weight = 2

[[menu.main]]
url = "/download/"
name = "Download"
weight = 3

# Social icons to be shown on the right-hand side of the navigation bar.
# The "name" field should match the name of the icon in Font Awesome.
# The list of available icons can be found at http://fontawesome.io/icons.


[[menu.icon]]
    url = "https://twitter.com/blackrocketnode"
    name = "fab fa-twitter"
    weight = 3

[[menu.icon]]
url = "https://t.me/oxipass"
name = "fab fa-telegram"
weight = 4

[[menu.icon]]
    url = "https://discord.gg/EMCt3R6hhq"
    name = "fab fa-discord"
    weight = 5

[[menu.icon]]
url = "https://github.com/oxipass"
name = "fab fa-github"
weight = 6

